In [45]:
import tensorflow as tf
import sys
import numpy as np

In [46]:
sys.path.append("../../../src/")

In [47]:
from models import LSTMModel

In [60]:
m = LSTMModel(10, 1)

In [64]:
m.load_weights("nstates_10/rep_0/train_weights/")

In [65]:
a = np.random.randn(3, 4, 10) 

In [66]:
m(a)

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[6.4009323],
        [7.363942 ],
        [5.1949368],
        [5.934023 ]],

       [[6.5598087],
        [6.2100897],
        [6.7641006],
        [5.601964 ]],

       [[6.5546174],
        [6.4606304],
        [3.1883488],
        [1.9488206]]], dtype=float32)>

In [67]:
m.trainable_weights

[<tf.Variable 'lstm_2/lstm_cell_2/kernel:0' shape=(10, 40) dtype=float32, numpy=
 array([[ 2.0739481 ,  0.06587394, -1.2344552 , -0.72299045, -0.08876126,
          0.27386448,  0.44561666, -0.53686494,  0.5577511 ,  0.40915146,
          1.9107751 , -0.07847258, -0.5867508 ,  0.47993553,  0.02409627,
         -0.04884553, -0.05781469, -0.11719214, -0.43095583,  0.16304871,
          1.0575924 ,  0.10337412,  0.48880473,  0.09128072,  0.10982425,
          0.11462029,  0.33679998, -0.22916995,  0.07830188,  0.36278632,
          1.8579029 , -0.54585904, -0.03558969,  0.06803299,  0.12078767,
          0.7925071 ,  0.01253734,  0.12769493, -0.5420918 , -0.5695482 ],
        [-0.38712895, -0.29222357,  0.5405123 ,  0.37323177,  0.6782929 ,
          0.4383201 ,  0.16523841, -0.6277051 , -0.5867983 , -0.04205866,
          0.13049054, -0.13561894, -0.02688843, -0.41414356,  0.40534005,
          0.16624647,  0.14294766, -0.46925718,  0.6209426 , -0.44021195,
          0.5001432 , -0.13805

In [52]:
trainable_count = np.sum([np.count_nonzero(w.numpy()) for w in m.trainable_weights])

In [53]:
trainable_count

4045001

In [70]:
h = 100
x = 10
y = 1
nlayers = 2

In [71]:
(4 * ((x + h) * h + h)) + h + y

44501

In [59]:
(4 * ((x + h) * h + h)) + (4 * ((h + h) * h + h)) + h + y

124901

In [29]:
trainable_count

851

In [68]:
124901/851

146.76968272620448

In [15]:
m.trainable_weights

[]

In [20]:
trainable_count = np.sum([ m.trainable_weights])

NameError: name 'K' is not defined

In [27]:
np.count_nonzero(m.trainable_weights[0].numpy())

400